### ISSUE TITLE
1.12 compatibility

### ISSUE THREAD

**Issue by MrBearLoL** [Skyost/OwnGarden#10]
Hey! i just find your plugin and it looks very good. This is just what i need. But i have a server with 1.12.2 version :/ Can you do the compatibility?

**Comment by Skyost** [comment]
Hey, sorry but I will not add a retro-compatibility. Reason is that 1.13 has been out for a while now, 1.14 will be out in some months.

But if you are able to make it using WorldEdit API, do not hesitate to submit a pull request :wink:

**Comment by knaxel** [comment]
> WorldEdit API, do n

I use the 1.12 version and know java. I am assuming you'll be okay if I continue the legacy builds? (ide credit the idea and any code I borrow of course)

**Comment by Skyost** [comment]
Yeah yeah no problem. What you could also do is to create an 1.12 extension : you adapt [this class](https://github.com/Skyost/OwnGarden/blob/master/src/main/java/fr/skyost/owngarden/worldedit/WorldEditOperations.java) for 1.12 (let's name it `WorldEditOperations1_12`), you keep the current one for 1.13 (and we could rename it `WorldEditOperations1_13`); both extending an abstract class `WorldEditOperations`. Then all you need is to create a loader which will load the class corresponding to the Bukkit version :wink:

**Comment by knaxel** [comment]
Actually it seams like the plugin config would need to be updated (or downdated? lol) as well because in 1.12 theres only one sapling material that uses byte data in game. Never had experience with loaders, let alone cross version plugins soo ill lyk how it goes.

**Comment by Skyost** [comment]
No problem :wink:
